# Generated by Django 3.2.13 on 2022-05-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_logged_id',
            new_name='is_logged_in',
        ),
    ]
